---
- name: Install Software
  xbps: pkg={{ item }} state=present
  with_items:
    - ConsoleKit2
    - adwaita-icon-theme
    - base-devel
    - cgmanager
    - feh
    - firefox
    - gedit
    - gnome-icon-theme
    - gnome-icon-theme-extras
    - gnome-icon-theme-symbolic
    - libressl-devel
    - lxde-icon-theme
    - lximage-qt
    - openbsd-netcat
    - python
    - python-devel
    - python-pip
    - wireshark-gtk
    - xxd

- name: Create TexSAW group
  group: name=texsaw state=present

# This user's password is published online so its not an issue that the hash is here (vagrant box)
- name: Create TexSAW user
  user:
    name: texsaw
    group: texsaw
    groups: users,wireshark,vagrant
    password: $6$rounds=656000$xCOMrsiwGOauNenT$Aw7veTM84NAIzWyGfbMpNduyQMP1e/NArkfLKgidocC2WeONVesEZA8Tbo90BWdeaDXE8Qj79JF2WEF1DENe8/
    state: present

- name: Enable ConsoleKit2
  file: src=/etc/sv/consolekit dest=/var/service/consolekit state=link

- name: Enable CGManager
  file: src=/etc/sv/cgmanager dest=/var/service/cgmanager state=link

- name: Get JD-GUI
  get_url:
    url: https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui-1.4.0.jar
    dest: /home/texsaw/jd-gui.jar
    owner: texsaw
    group: texsaw
    mode: 0755
