Vagrant.configure("2") do |config|
  config.vm.box = "TexSAW16"
  config.vm.box_url = "http://texsaw.utdallas.edu/resources/TexSAW.box"
  config.vm.synced_folder "shared-data", "/home/texsaw/Desktop/shared-data",
                          owner: "texsaw", group: "texsaw", create: "true"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
end
